version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - serverless deploy --stage ${STAGE_NAME} 

cache:
  paths:
    - node_modules